### ISSUE TITLE
Bring up code coverage

### ISSUE THREAD

**Issue by ianyong** [AY2021S1-CS2103T-W16-3/tp#115]
Code coverage is currently at 69.29%. The aim is to bring this up to 100%.

**Comment by ianyong** [comment]
Pushed back to v1.4 so as to devote more time to developing and polishing features.

**Comment by siddarth2824** [comment]
Wrote tests for `FinanceTrackerParser` for commands related to `BookmarkTransactions` such as:
* `AddBookmarkIncome`
* `AddBookmarkExpense`
* `DeleteBookmark`
* `EditBookmark`
* `ConvertBookmark`

**Comment by ianyong** [comment]
Code coverage currently stands at 90.05%.
