### ISSUE TITLE
Filtered lists no longer update automatically

### ISSUE THREAD

**Issue by ianyong** [AY2021S1-CS2103T-W16-3/tp#128]
The `ExpenseList` and `IncomeList` have to be reloaded after a transaction is added/edited/deleted in order to view the latest state of the list.

First noticed in #123.

**Comment by yongping827** [comment]
Possible solutions:
* Add a switch statement that refreshes the tab after every command.
* Modify `CommandResult` to indicate any changes.
* Make use of listener, somehow.
* Add additional getters for the lists or for the transactions based on index.
