### ISSUE TITLE
Add frequent expense feature

### ISSUE THREAD

**Issue by siddarth2824** [AY2021S1-CS2103T-W16-3/tp#139]
Allow users to add expenses that occur frequently. This will enable users to then add those frequent expenses as a completed expense to the tracker in a convenient way. The tracker will have a frequent expense list to store all of the user's frequent expenses.

The frequent expense feature functionality consists of:
1. Add a frequent expense to the frequent expense list.
2. Edit an existing frequent expense.
3. Delete an existing frequent expense.
4. Convert an existing frequent expense to an expense and add it to the tracker.

**Comment by wltan** [comment]
Closed with #136
