### ISSUE TITLE
Update trailing whitespace check to always fail when a trailing whitespace is encountered

### ISSUE THREAD

**Issue by ianyong** [AY2021S1-CS2103T-W16-3/tp#151]
Currently, the trailing whitespace check only prints warnings for trailing whitespace in Markdown files. This is quite annoying for everyone whenever a trailing whitespace is accidentally introduced in the documentation, as everyone sees the warning every time they push to remote (due to the Git pre-push hook).

**Comment by wltan** [comment]
Issue still persists because the wrong file was changed.
