### ISSUE TITLE
Inconsistent tab switching behaviour

### ISSUE THREAD

**Issue by zhaojj2209** [AY2021S1-CS2103T-W16-3/tp#270]
Currently, the `add-expense`/`add-income` commands do not switch to the respective tabs, while `add-bookmark-expense` and `add-bookmark-income` do. 

The `add-expense`/`add-income` commands should switch the app to the Expenses/Incomes tab respectively when executed. However, if executed on the Overview tab, the tab should not be switched.

The `set-expense-limit` and `set-savings-goal` commands should also switch the app to the Overview tab.

**Comment by wltan** [comment]
Tagging this as a bug because it is undocumented behavior in the user guide, so testers can flag this as a potential bug.
