### ISSUE TITLE
Update behaviour for commands that do not take in any arguments

### ISSUE THREAD

**Issue by ianyong** [AY2021S1-CS2103T-W16-3/tp#280]
Currently, commands that do not take in any arguments such as `help`, `clear`, and `exit` work regardless of what is typed after the command keyword. While I do not think that this behaviour is an issue, it might be a point of contention should someone file this as a bug report during the practical exam.

**Comment by wltan** [comment]
Tagging this as a bug because it is undocumented behavior in the user guide (as noted in the description), so testers can flag this as a potential bug.
