### ISSUE TITLE
Rename seedu.address.model classes

### ISSUE THREAD

**Issue by yongping827** [AY2021S1-CS2103T-W16-3/tp#38]
Rename classes as:
- Person &rarr; Transaction
  - Name &rarr; Name
  - Phone &rarr; Amount
  - Tags &rarr; Category
  - Email &rarr; Date
  - Address &rarr; (deleted)

**Comment by wltan** [comment]
Note that while we intend to rename test methods to match the new model, we will leave the test data alone for now and revisit it in a follow-up issue.

**Comment by wltan** [comment]
Now that #39 has been merged, all that is left is to delete the `Address` class, which is incidentally one of the CS2103T tP tutorial tasks.
