### ISSUE TITLE
Sample usage inconsistent with validation

### ISSUE THREAD

**Issue by zhaojj2209** [AY2021S1-CS2103T-W16-3/tp#78]
The current sample add expense command usage is invalid as the category input is limited to alphanumeric values only.

<img width="653" alt="Screenshot 2020-10-09 at 12 59 34 PM" src="https://user-images.githubusercontent.com/54243224/95548216-32ff4000-0a37-11eb-9f39-ab210e8c210e.png">

**Comment by wltan** [comment]
How should we rectify this? Fix the sample command or fix the validation?
